sudo: required
language: java
jdk: oraclejdk8
addons:
  ssh_known_hosts:
  - 47.94.231.67:22008
  - 47.94.10.122:22008
cache:
  directories:
    - '$HOME/.sonar/cache'
script:
- sh litetokens.sh
- "./gradlew build"
- "./gradlew jacocoTestReport"
- bash deploy.sh

after_success:
- "bash <(curl -s https://codecov.io/bash) -t 060bb400-c6fe-4d5f-a6c8-427105c746ac -s build/reports/jacoco/"

skip_build:
- README.md：
- LICENSE




